server:
  port: 8192

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
          lower-case-service-id: true

# EUREKA
eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8191/eureka/